version: '3.2'
services:
  mongodb:
    build: ./mongodb
    volumes:
    - ./mongodb/data:/data/db/output
    ports:
    - ${MONGO_PORT}:27017
    env_file:
    - .env
    networks:
      mynet:
        ipv4_address: 172.28.2.1
  node1:
    build: ./event_generator
    ports:
    - 8001:8001
    command:
    - python
    - node_server.py
    - -p
    - '8001'
    networks:
      mynet:
        ipv4_address: 172.28.1.1
  analyzer:
    build: ./analyzer
    ports:
    - 8002:8002
    command:
    - python
    - node_analyzer.py
    - -p
    - '8002'
    networks:
      mynet:
        ipv4_address: 172.28.1.2
networks:
  mynet:
    ipam:
      driver: default
      config:
      - subnet: 172.28.1.0/16
